"""Explicit API contracts shared by Flask and future FastAPI adapters."""

from .models import (
    AssetField,
    AssetItem,
    AssetPageResponse,
    AssetTableRequest,
    DataEnvelope,
    FieldMappingItem,
    FieldMappingListResponse,
    FieldMappingTableItem,
    FieldMappingTableListResponse,
    ErrorEnvelope,
    ErrorModel,
    IndicatorItem,
    IndicatorRequest,
    IndicatorListResponse,
    ItemsResponse,
    MessageDataResponse,
    ReportItem,
    ReportListResponse,
    ReportRequest,
    MappingStats,
    SourceSystem,
    SourceSystemListResponse,
)
from .validation import validate_contract

__all__ = [
    "AssetField",
    "AssetItem",
    "AssetPageResponse",
    "AssetTableRequest",
    "DataEnvelope",
    "ErrorEnvelope",
    "FieldMappingItem",
    "FieldMappingListResponse",
    "FieldMappingTableItem",
    "FieldMappingTableListResponse",
    "ErrorModel",
    "IndicatorItem",
    "IndicatorListResponse",
    "IndicatorRequest",
    "ItemsResponse",
    "MessageDataResponse",
    "ReportItem",
    "ReportListResponse",
    "ReportRequest",
    "MappingStats",
    "SourceSystem",
    "SourceSystemListResponse",
    "validate_contract",
]
