-- Reference only; this file is not used at runtime and is not the canonical menu source.
-- The PostgreSQL baseline schema is backend/schema/postgresql.sql.
-- Default application menus are defined once in config/default-menus.json and seeded by
-- backend/app/navigation/persistence.py through schema_migrate.py apply.
-- Do not add CREATE SCHEMA/TABLE/INDEX or default-menu INSERT statements here.
