import { requestRemote } from "./http.js";
import { API_ASSETS } from "../data/apiAssets.ts";
import { SYSTEMS } from "../data/systems.ts";
const remote=(import.meta.env.VITE_API_MODE||"mock").trim().toLowerCase()==="remote";
let store=JSON.parse(JSON.stringify(API_ASSETS)); const clone=(value)=>JSON.parse(JSON.stringify(value));
export async function getApiAssets(params={}) { if(remote){const r=await requestRemote("/api-assets",{params});return r.items||[];} const q=String(params.keyword||"").toLowerCase();return clone(store.filter(x=>(!params.status||x.status===params.status)&&(!params.method||x.method===params.method)&&(!params.downstreamSystemId||String(x.downstreamSystemId)===String(params.downstreamSystemId))&&(!q||[x.code,x.name,x.path,x.description,x.ownerName,x.downstreamSystemName,x.downstreamSystemShortName].some(v=>String(v||"").toLowerCase().includes(q))))); }
export async function getApiDownstreamSystems(keyword="") { if(remote){const r=await requestRemote("/api-assets/systems",{params:{keyword}});return r.items||[];} const q=String(keyword).trim().toLowerCase();return clone(SYSTEMS.filter(x=>!q||[x.name,x.short_name,x.code].some(v=>String(v||"").toLowerCase().includes(q)))); }
export async function saveApiAsset(code,payload){if(remote)return requestRemote(code?`/api-assets/${encodeURIComponent(code)}`:"/api-assets",{method:code?"PUT":"POST",body:payload}); if(code){store=store.map(x=>x.code===code?clone(payload):x);}else{if(store.some(x=>x.code===payload.code))throw new Error("API 编码已存在");store=[clone(payload),...store];}return clone(payload);}
export async function deleteApiAsset(code){if(remote)return requestRemote(`/api-assets/${encodeURIComponent(code)}`,{method:"DELETE"});store=store.filter(x=>x.code!==code);}
export async function setApiAssetStatus(code,status){if(remote)return requestRemote(`/api-assets/${encodeURIComponent(code)}/status`,{method:"PATCH",body:{status}});const item=store.find(x=>x.code===code);if(item)item.status=status;return clone(item);}
export async function replaceApiAssetRows(code,key,items){const endpoints={params:"params",responseFields:"response-fields",relations:"relations"};if(remote)return requestRemote(`/api-assets/${encodeURIComponent(code)}/${endpoints[key]}`,{method:"PUT",body:{items}});const item=store.find(x=>x.code===code);if(item)item[key]=clone(items);return clone(item);}
