#!/usr/bin/env python3
"""Generate replayable PostgreSQL/DWS SQL from the safe retail demo datasets.

This is the ONLY supported way to obtain SQL-form demo data in the community
repository: every row originates from demo/datasets/*.json (fictional retail
data). It never reads from a live database and never exports real business data.

Output defaults to a git-ignored directory (tmp/demo-sql/). If you need the SQL
inside the repository for a public guide, generate it locally and review the
diff before committing.

Usage:
  python demo/generate_demo_sql.py                      # -> tmp/demo-sql/
  python demo/generate_demo_sql.py --output demo/generated  # explicit target
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REPO_ROOT = ROOT.parent
DEFAULT_OUTPUT = REPO_ROOT / "tmp" / "demo-sql"


def literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


def infer_sql_type(values):
    if all(isinstance(v, bool) for v in values):
        return "BOOLEAN"
    if all(isinstance(v, int) for v in values):
        return "BIGINT"
    if all(isinstance(v, (int, float)) for v in values):
        return "NUMERIC"
    return "TEXT"


def build_dataset_sql(table_name: str, rows: list[dict]) -> str:
    if not rows:
        return f"-- {table_name}: empty dataset\n"
    columns = list(rows[0].keys())
    col_sql = ", ".join(columns)
    type_sql = ",\n    ".join(
        f"{col} {infer_sql_type([row.get(col) for row in rows])}" for col in columns
    )
    lines = [
        f"-- Generated by demo/generate_demo_sql.py from demo/datasets/{table_name}.json",
        f"-- Source: fictional full-channel retail demo data (see demo/manifest.json)",
        "",
        f"CREATE TABLE IF NOT EXISTS public.{table_name} (",
        f"    {type_sql}",
        ");",
        "",
        "TRUNCATE TABLE public.{0};".format(table_name),
        "",
    ]
    insert_head = f"INSERT INTO public.{table_name} ({col_sql}) VALUES"
    for row in rows:
        vals = ", ".join(literal(row.get(col)) for col in columns)
        lines.append(insert_head)
        lines.append(f"    ({vals});")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate SQL demo data from the safe retail datasets."
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help=f"Target output directory (default: {DEFAULT_OUTPUT.relative_to(REPO_ROOT)})",
    )
    args = parser.parse_args()

    manifest = json.loads((ROOT / "manifest.json").read_text(encoding="utf-8"))
    output_dir = Path(args.output).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    entry_lines = [
        "-- Generated by demo/generate_demo_sql.py from demo/datasets/*.json",
        "-- Fictional full-channel retail demo data only.",
        "",
    ]
    for relative in manifest["datasets"]:
        dataset_name = Path(relative).stem
        rows = json.loads((ROOT / relative).read_text(encoding="utf-8"))
        sql_text = build_dataset_sql(dataset_name, rows)
        (output_dir / f"{dataset_name}.sql").write_text(sql_text, encoding="utf-8")
        entry_lines.append(f"\\i {dataset_name}.sql")
        print(f"  [OK] {dataset_name}.sql  rows={len(rows)}")

    (output_dir / "all-datasets.sql").write_text("\n".join(entry_lines) + "\n", encoding="utf-8")
    print(f"\nSQL demo generated at: {output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
